// Is this even partly correct?
// This also seems a little too optimistic, especially the <expr> part
program
  : statement+
  ;

statement
  : LABEL_DECL SEPERATOR+ instruction EOS
  | SEPERATOR* instruction EOS

instruction
  : instruction_name
  | instruction_name SEPERATOR+ arg
  | instruction_name SEPERATOR+ arg ARG_SEP SEPERATOR* arg

instruction
 : STRING
 | STRING '.' NUMBER
 ;

arg
 : expr
 ;

expr
 : NUMBER
 | CHAR
 | REGISTER
 | LABEL
 | DEREF_START expr DEREF_END
 | expr OPERATION expr
 ;

OPERATION
 : '+'
 | '-'
 | '*'
 | '/'
 ;

DEREF_START
 : '['
 ;

REREF_END
 | ']'
 ;

EOS
 : ';'
 | EOL
 ;

EOL
 : '\n'
 ;

STRING
 : [a-z_]+
 ;

NUMBER
 : [0-9]+
 | '0x' [0-9a-fA-F]+
 ;

CHAR:
 : '\'' [A-z0-9] '\''

REGISTER
 : 'r' NUMBER
 ;

LABEL
 : STRING
 ;

LABEL_DECL
 : STRING ':'
 ;

SEPERATOR
 : ' '
 | EOL
 ;

ARG_SEP
 : ','
 ;
